### ISSUE TITLE
Create git repo on import when needed

### ISSUE THREAD

**Issue by archcorsair** [steelbrain/bibi#6]
When trying to import using `bibi import` and a git repo is not initiated, the user receives this error:

```
Error: Either current directory is not a git repository or it doesnt have a valid remote "origin"
```

Let's add the ability to create a git repo and prompt for origin credentials.

**Comment by steelbrain** [comment]
The import command has been removed, bibi tries to do a few things and do them good instead of try to half-do a lot of things now
